// UI
const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
const SET_LIST_VIEW = "SET_LIST_VIEW";
const SET_GRID_VIEW = "SET_GRID_VIEW";

const PRODUCTS_FETCH_BEGIN = "PRODUCTS_FETCH_BEGIN";
const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS";
const PRODUCTS_FETCH_ERROR = "PRODUCTS_FETCH_ERROR";

const SINGLE_PRODUCT_FETCH_BEGIN = "SINGLE_PRODUCT_FETCH_BEGIN";
const SINGLE_PRODUCT_FETCH_SUCCESS = "SINGLE_PRODUCT_FETCH_SUCCESS";
const SINGLE_PRODUCT_FETCH_ERROR = "SINGLE_PRODUCT_FETCH_ERROR";

export {
  OPEN_SIDEBAR,
  CLOSE_SIDEBAR,
  SET_LIST_VIEW,
  SET_GRID_VIEW,
  PRODUCTS_FETCH_BEGIN,
  PRODUCTS_FETCH_SUCCESS,
  PRODUCTS_FETCH_ERROR,
  SINGLE_PRODUCT_FETCH_BEGIN,
  SINGLE_PRODUCT_FETCH_SUCCESS,
  SINGLE_PRODUCT_FETCH_ERROR,
};
