// UI
const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
const SET_LIST_VIEW = "SET_LIST_VIEW";
const SET_GRID_VIEW = "SET_GRID_VIEW";

// PRODUCTS
const PRODUCTS_FETCH_BEGIN = "PRODUCTS_FETCH_BEGIN";
const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS";
const PRODUCTS_FETCH_ERROR = "PRODUCTS_FETCH_ERROR";

const SINGLE_PRODUCT_FETCH_BEGIN = "SINGLE_PRODUCT_FETCH_BEGIN";
const SINGLE_PRODUCT_FETCH_SUCCESS = "SINGLE_PRODUCT_FETCH_SUCCESS";
const SINGLE_PRODUCT_FETCH_ERROR = "SINGLE_PRODUCT_FETCH_ERROR";

// FILTER
const SET_PRODUCTS = "SET_PRODUCTS";
const UPDATE_FILTER = "UPDATE_FILTER";
const CLEAR_FILTER = "CLEAR_FILTER";
const SORT_PRODUCTS = "SORT_PRODUCTS";
const SORT_LOWEST = "SORT_LOWEST";
const SORT_HIGHEST = "SORT_HIGHEST";
const SORT_NAME_ASC = "SORT_NAME_ASC";
const SORT_NAME_DESC = "SORT_NAME_DESC";

// CART
const ADD_TO_CART = "ADD_TO_CART";
const ADD_ITEM_QUANTITY = "ADD_ITEM_QUANTITY";
const REMOVE_ITEM_QUANTITY = "REMOVE_ITEM_QUANTITY";
const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
const CLEAR_CART = "CLEAR_CART";
const CART_CHECKOUT = "CART_CHECKOUT";

export {
  OPEN_SIDEBAR,
  CLOSE_SIDEBAR,
  SET_LIST_VIEW,
  SET_GRID_VIEW,
  PRODUCTS_FETCH_BEGIN,
  PRODUCTS_FETCH_SUCCESS,
  PRODUCTS_FETCH_ERROR,
  SINGLE_PRODUCT_FETCH_BEGIN,
  SINGLE_PRODUCT_FETCH_SUCCESS,
  SINGLE_PRODUCT_FETCH_ERROR,
  SET_PRODUCTS,
  UPDATE_FILTER,
  CLEAR_FILTER,
  SORT_PRODUCTS,
  SORT_LOWEST,
  SORT_HIGHEST,
  SORT_NAME_ASC,
  SORT_NAME_DESC,
  ADD_TO_CART,
  ADD_ITEM_QUANTITY,
  REMOVE_ITEM_QUANTITY,
  REMOVE_CART_ITEM,
  CLEAR_CART,
  CART_CHECKOUT,
};
