// UI
const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
const SET_LIST_VIEW = "SET_LIST_VIEW";
const SET_GRID_VIEW = "SET_GRID_VIEW";

// PRODUCTS
const PRODUCTS_FETCH_BEGIN = "PRODUCTS_FETCH_BEGIN";
const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS";
const PRODUCTS_FETCH_ERROR = "PRODUCTS_FETCH_ERROR";

const SINGLE_PRODUCT_FETCH_BEGIN = "SINGLE_PRODUCT_FETCH_BEGIN";
const SINGLE_PRODUCT_FETCH_SUCCESS = "SINGLE_PRODUCT_FETCH_SUCCESS";
const SINGLE_PRODUCT_FETCH_ERROR = "SINGLE_PRODUCT_FETCH_ERROR";

// FILTER
const GET_SEARCH = "GET_SEARCH";
const SET_CATEGORY = "SET_CATEGORY";
const SET_COMPANY = "SET_COMPANY";
const SET_COLOR = "SET_COLOR";
const SET_PRICE = "SET_PRICE";
const SET_SHIPPING = "SET_SHIPPING";
const SORT_LOWEST = "SORT_LOWEST";
const SORT_HIGHEST = "SORT_HIGHEST";
const SORT_NAME_ASC = "SORT_NAME_ASC";
const SORT_NAME_DESC = "SORT_NAME_DESC";
const SET_FILTER_CLEAR = "SET_FILTER_CLEAR";

export {
  OPEN_SIDEBAR,
  CLOSE_SIDEBAR,
  SET_LIST_VIEW,
  SET_GRID_VIEW,
  PRODUCTS_FETCH_BEGIN,
  PRODUCTS_FETCH_SUCCESS,
  PRODUCTS_FETCH_ERROR,
  SINGLE_PRODUCT_FETCH_BEGIN,
  SINGLE_PRODUCT_FETCH_SUCCESS,
  SINGLE_PRODUCT_FETCH_ERROR,
  GET_SEARCH,
  SET_CATEGORY,
  SET_COMPANY,
  SET_COLOR,
  SET_PRICE,
  SET_SHIPPING,
  SORT_HIGHEST,
  SORT_LOWEST,
  SORT_NAME_ASC,
  SORT_NAME_DESC,
  SET_FILTER_CLEAR,
};
